CELL_SIZE = 30

CELL_COLOR = "lightgray"
CELL_WIDTH = 0.01

VERTEX_COLOR = "#FF4422"
VERTEX_OUTLINE_COLOR = "lightgray"
VERTEX_RADIUS = CELL_SIZE / 4
VERTEX_CLICK_RADIUS = CELL_SIZE / 2.2
VERTEX_TITLE_COLOR = "#912E1C"
VERTEX_TITLE_SIZE = 20

EDGE_COLOR = "#232423"
EDGE_WIDTH = 4

SELECTION_COLOR = "#0000AA"
SELECTION_WIDTH = 5

WEIGHT_COLOR = "#FF4422"
WEIGHT_SIZE = 16
